package varasto;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.05.06 11:25:00 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class TulosTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi162 */
  @Test
  public void testRekisteroi162() {    // Tulos: 162
    Tulos tulos1 = new Tulos(); 
    assertEquals("From: Tulos line: 164", 0, tulos1.getTunnusNro()); 
    tulos1.rekisteroi(); 
    Tulos tulos2 = new Tulos(); 
    tulos2.rekisteroi(); 
    int n1 = tulos1.getTunnusNro(); 
    int n2 = tulos2.getTunnusNro(); 
    assertEquals("From: Tulos line: 170", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse306 */
  @Test
  public void testParse306() {    // Tulos: 306
    Tulos tulos = new Tulos(); 
    tulos.parse("   2  |  1  |  Penkki  |  5x5  |  100kg  |  väsytti"); 
    assertEquals("From: Tulos line: 309", 2, tulos.getTunnusNro()); 
    assertEquals("From: Tulos line: 310", 1, tulos.getPaivaNro()); 
    assertEquals("From: Tulos line: 311", "2 1 Penkki 5x5 100kg väsytti", tulos.tulosta(System.out)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna379 */
  @Test
  public void testAnna379() {    // Tulos: 379
    Tulos tulos = new Tulos(); 
    tulos.parse("   2  |  1  |  Penkki  |  5x5  |  100kg  |  väsytti"); 
    assertEquals("From: Tulos line: 382", "2", tulos.anna(0)); 
    assertEquals("From: Tulos line: 383", "1", tulos.anna(1)); 
    assertEquals("From: Tulos line: 384", "Penkki", tulos.anna(2)); 
    assertEquals("From: Tulos line: 385", "5x5", tulos.anna(3)); 
    assertEquals("From: Tulos line: 386", "100kg", tulos.anna(4)); 
    assertEquals("From: Tulos line: 387", "väsytti", tulos.anna(5)); 
  } // Generated by ComTest END
}