package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.05.06 12:14:34 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PaivaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi85 */
  @Test
  public void testRekisteroi85() {    // Paiva: 85
    Paiva aku1 = new Paiva(); 
    assertEquals("From: Paiva line: 87", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    Paiva aku2 = new Paiva(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTunnusNro(); 
    int n2 = aku2.getTunnusNro(); 
    assertEquals("From: Paiva line: 93", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse248 */
  @Test
  public void testParse248() {    // Paiva: 248
    Paiva paiva = new Paiva(); 
    paiva.parse("   3  |  10.10.2000   | penkki"); 
    assertEquals("From: Paiva line: 251", 3, paiva.getTunnusNro()); 
    assertEquals("From: Paiva line: 252", true, paiva.toString().startsWith("=/=003Treenin tyyppi: penkki=/="));  // on enemmäkin kuin 3 kenttää, siksi loppu |
    paiva.rekisteroi(); 
    int n = paiva.getTunnusNro(); 
    paiva.parse(""+(n+20));  // Otetaan merkkijonosta vain tunnusnumero
    paiva.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Paiva line: 258", n+20+1, paiva.getTunnusNro()); 
  } // Generated by ComTest END
}