package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.14 14:20:28 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class PaivaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi60 */
  @Test
  public void testRekisteroi60() {    // Paiva: 60
    Paiva aku1 = new Paiva(); 
    assertEquals("From: Paiva line: 62", 0, aku1.getTunnusNro()); 
    aku1.rekisteroi(); 
    Paiva aku2 = new Paiva(); 
    aku2.rekisteroi(); 
    int n1 = aku1.getTunnusNro(); 
    int n2 = aku2.getTunnusNro(); 
    assertEquals("From: Paiva line: 68", n2-1, n1); 
  } // Generated by ComTest END
}