package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.03 09:23:16 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreenipaivakirjaTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa35 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa35() throws SailoException {    // Treenipaivakirja: 35
    Treenipaivakirja treenipaivakirja = new Treenipaivakirja(); 
    Paiva abc = new Paiva(), ggg = new Paiva(); 
    abc.rekisteroi(); ggg.rekisteroi(); 
    assertEquals("From: Treenipaivakirja line: 40", 0, treenipaivakirja.getPaivia()); 
    treenipaivakirja.lisaa(abc); assertEquals("From: Treenipaivakirja line: 41", 1, treenipaivakirja.getPaivia()); 
    treenipaivakirja.lisaa(ggg); assertEquals("From: Treenipaivakirja line: 42", 2, treenipaivakirja.getPaivia()); 
    treenipaivakirja.lisaa(abc); assertEquals("From: Treenipaivakirja line: 43", 3, treenipaivakirja.getPaivia()); 
    assertEquals("From: Treenipaivakirja line: 44", 3, treenipaivakirja.getPaivia()); 
    assertEquals("From: Treenipaivakirja line: 45", abc, treenipaivakirja.annaPaiva(0)); 
    assertEquals("From: Treenipaivakirja line: 46", ggg, treenipaivakirja.annaPaiva(1)); 
    assertEquals("From: Treenipaivakirja line: 47", abc, treenipaivakirja.annaPaiva(2)); 
    try {
    assertEquals("From: Treenipaivakirja line: 48", abc, treenipaivakirja.annaPaiva(3)); 
    fail("Treenipaivakirja: 48 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    treenipaivakirja.lisaa(abc); assertEquals("From: Treenipaivakirja line: 49", 4, treenipaivakirja.getPaivia()); 
    treenipaivakirja.lisaa(abc); assertEquals("From: Treenipaivakirja line: 50", 5, treenipaivakirja.getPaivia()); 
    try {
    treenipaivakirja.lisaa(abc); 
    fail("Treenipaivakirja: 51 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}