package treenipaivakirja.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.14 20:05:25 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TreenipaivakirjaTest {



  // Generated by ComTest BEGIN
  /** testAnnaTulokset40 */
  @Test
  public void testAnnaTulokset40() {    // Treenipaivakirja: 40
    Treenipaivakirja treenipaivakirja = new Treenipaivakirja(); 
    Paiva aku1 = new Paiva(), aku2 = new Paiva(), aku3 = new Paiva(); 
    aku1.rekisteroi(); aku2.rekisteroi(); aku3.rekisteroi(); 
    int id1 = aku1.getTunnusNro(); 
    int id2 = aku2.getTunnusNro(); 
    Tulos pitsi11 = new Tulos(id1); treenipaivakirja.lisaa(pitsi11); 
    Tulos pitsi12 = new Tulos(id1); treenipaivakirja.lisaa(pitsi12); 
    Tulos pitsi21 = new Tulos(id2); treenipaivakirja.lisaa(pitsi21); 
    Tulos pitsi22 = new Tulos(id2); treenipaivakirja.lisaa(pitsi22); 
    Tulos pitsi23 = new Tulos(id2); treenipaivakirja.lisaa(pitsi23); 
    List<Tulos> loytyneet; 
    loytyneet = treenipaivakirja.annaTulokset(aku3); 
    assertEquals("From: Treenipaivakirja line: 56", 0, loytyneet.size()); 
    loytyneet = treenipaivakirja.annaTulokset(aku1); 
    assertEquals("From: Treenipaivakirja line: 58", 2, loytyneet.size()); 
    assertEquals("From: Treenipaivakirja line: 59", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Treenipaivakirja line: 60", true, loytyneet.get(1) == pitsi12); 
    loytyneet = treenipaivakirja.annaTulokset(aku2); 
    assertEquals("From: Treenipaivakirja line: 62", 3, loytyneet.size()); 
    assertEquals("From: Treenipaivakirja line: 63", true, loytyneet.get(0) == pitsi21); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa88 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa88() throws SailoException {    // Treenipaivakirja: 88
    Treenipaivakirja treenipaivakirja = new Treenipaivakirja(); 
    Paiva abc = new Paiva(), ggg = new Paiva(); 
    abc.rekisteroi(); ggg.rekisteroi(); 
    assertEquals("From: Treenipaivakirja line: 93", 0, treenipaivakirja.getPaivia()); 
    treenipaivakirja.lisaa(abc); assertEquals("From: Treenipaivakirja line: 94", 1, treenipaivakirja.getPaivia()); 
    treenipaivakirja.lisaa(ggg); assertEquals("From: Treenipaivakirja line: 95", 2, treenipaivakirja.getPaivia()); 
    treenipaivakirja.lisaa(abc); assertEquals("From: Treenipaivakirja line: 96", 3, treenipaivakirja.getPaivia()); 
    assertEquals("From: Treenipaivakirja line: 97", 3, treenipaivakirja.getPaivia()); 
    assertEquals("From: Treenipaivakirja line: 98", abc, treenipaivakirja.annaPaiva(0)); 
    assertEquals("From: Treenipaivakirja line: 99", ggg, treenipaivakirja.annaPaiva(1)); 
    assertEquals("From: Treenipaivakirja line: 100", abc, treenipaivakirja.annaPaiva(2)); 
    try {
    assertEquals("From: Treenipaivakirja line: 101", abc, treenipaivakirja.annaPaiva(3)); 
    fail("Treenipaivakirja: 101 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    treenipaivakirja.lisaa(abc); assertEquals("From: Treenipaivakirja line: 102", 4, treenipaivakirja.getPaivia()); 
    treenipaivakirja.lisaa(abc); assertEquals("From: Treenipaivakirja line: 103", 5, treenipaivakirja.getPaivia()); 
    try {
    treenipaivakirja.lisaa(abc); 
    fail("Treenipaivakirja: 104 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}