package treenipaivakirja.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.05.08 15:32:22 // Generated by ComTest
 *
 */
@SuppressWarnings({ "PMD" })
public class TuloksetTest {


  // Generated by ComTest BEGIN  // Tulokset: 25

  private Tulokset tulokset; 
  private String tiedNimi; 
  private File ftied; 

  @Before
  public void alusta() throws SailoException {
     tiedNimi = "testailutulokset"; 
     ftied = new File(tiedNimi+".db"); 
     ftied.delete(); 
     tulokset = new Tulokset(tiedNimi); 
  }

  @After
  public void siivoa() {
     ftied.delete(); 
  }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKorvaaTaiLisaa192 
   * @throws CloneNotSupportedException when error
   * @throws SailoException when error
   */
  @Test
  public void testKorvaaTaiLisaa192() throws CloneNotSupportedException, SailoException {    // Tulokset: 192
    Tulokset tulokset = new Tulokset("testi"); 
    Tulos tulos1 = new Tulos(), tulos2 = new Tulos(); 
    tulos1.vastaaTulos(); 
    tulos2.vastaaTulos(); 
    tulos1.rekisteroi(); tulos2.rekisteroi(); 
    assertEquals("From: Tulokset line: 201", 0, tulokset.getLkm()); 
    tulokset.korvaaTaiLisaa(tulos1); 
    assertEquals("From: Tulokset line: 203", 1, tulokset.getLkm()); 
    tulokset.korvaaTaiLisaa(tulos2); 
    assertEquals("From: Tulokset line: 205", 2, tulokset.getLkm()); 
    Tulos tulos3 = tulos1.clone(); 
    tulos3.aseta(2, "xxx"); 
    Iterator<Tulos> it = tulokset.iterator(); 
    assertEquals("From: Tulokset line: 209", tulos1, it.next()); 
    tulokset.korvaaTaiLisaa(tulos3); assertEquals("From: Tulokset line: 210", 2, tulokset.getLkm()); 
    it = tulokset.iterator(); 
    Tulos t1 = it.next(); 
    Tulos t2 = it.next(); 
    assertEquals("From: Tulokset line: 214", tulos3, t1); 
    assertEquals("From: Tulokset line: 215", tulos2, t2); 
    assertEquals("From: Tulokset line: 216", t1.getTunnusNro(), tulos1.getTunnusNro()); 
    assertEquals("From: Tulokset line: 217", t2.getTunnusNro(), tulos2.getTunnusNro()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testAnnaTulokset281 
   * @throws SailoException when error
   */
  @Test
  public void testAnnaTulokset281() throws SailoException {    // Tulokset: 281
    Tulos tulos21 = new Tulos(2); tulos21.vastaaTulos(2); tulokset.lisaa(tulos21); 
    Tulos tulos11 = new Tulos(1); tulos11.vastaaTulos(1); tulokset.lisaa(tulos11); 
    Tulos tulos22 = new Tulos(2); tulos22.vastaaTulos(2); tulokset.lisaa(tulos22); 
    Tulos tulos12 = new Tulos(1); tulos12.vastaaTulos(1); tulokset.lisaa(tulos12); 
    Tulos tulos23 = new Tulos(2); tulos23.vastaaTulos(2); tulokset.lisaa(tulos23); 
    Tulos tulos51 = new Tulos(5); tulos51.vastaaTulos(5); tulokset.lisaa(tulos51); 
    List<Tulos> loytyneet; 
    loytyneet = tulokset.annaTulokset(3); 
    assertEquals("From: Tulokset line: 294", 0, loytyneet.size()); 
    loytyneet = tulokset.annaTulokset(1); 
    assertEquals("From: Tulokset line: 296", 2, loytyneet.size()); 
    assertEquals("From: Tulokset line: 298", tulos11, loytyneet.get(0)); 
    assertEquals("From: Tulokset line: 299", tulos12, loytyneet.get(1)); 
    loytyneet = tulokset.annaTulokset(5); 
    assertEquals("From: Tulokset line: 302", 1, loytyneet.size()); 
    assertEquals("From: Tulokset line: 303", tulos51, loytyneet.get(0)); 
  } // Generated by ComTest END
}