package treenipaivakirja.test;
// Generated by ComTest BEGIN
import treenipaivakirja.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.03.14 19:55:30 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TuloksetTest {



  // Generated by ComTest BEGIN
  /** testIterator63 */
  @Test
  public void testIterator63() {    // Tulokset: 63
    Tulokset tulokset = new Tulokset(); 
    Tulos pitsi21 = new Tulos(2); tulokset.lisaa(pitsi21); 
    Tulos pitsi11 = new Tulos(1); tulokset.lisaa(pitsi11); 
    Tulos pitsi22 = new Tulos(2); tulokset.lisaa(pitsi22); 
    Tulos pitsi12 = new Tulos(1); tulokset.lisaa(pitsi12); 
    Tulos pitsi23 = new Tulos(2); tulokset.lisaa(pitsi23); 
    Iterator<Tulos> i2=tulokset.iterator(); 
    assertEquals("From: Tulokset line: 75", pitsi21, i2.next()); 
    assertEquals("From: Tulokset line: 76", pitsi11, i2.next()); 
    assertEquals("From: Tulokset line: 77", pitsi22, i2.next()); 
    assertEquals("From: Tulokset line: 78", pitsi12, i2.next()); 
    assertEquals("From: Tulokset line: 79", pitsi23, i2.next()); 
    try {
    assertEquals("From: Tulokset line: 80", pitsi12, i2.next()); 
    fail("Tulokset: 80 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Tulos har:tulokset ) {
    assertEquals("From: Tulokset line: 86", jnrot[n], har.getPaivaNro()); n++; 
    }
    assertEquals("From: Tulokset line: 89", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaTulokset106 */
  @Test
  public void testAnnaTulokset106() {    // Tulokset: 106
    Tulokset tulokset = new Tulokset(); 
    Tulos pitsi21 = new Tulos(2); tulokset.lisaa(pitsi21); 
    Tulos pitsi11 = new Tulos(1); tulokset.lisaa(pitsi11); 
    Tulos pitsi22 = new Tulos(2); tulokset.lisaa(pitsi22); 
    Tulos pitsi12 = new Tulos(1); tulokset.lisaa(pitsi12); 
    Tulos pitsi23 = new Tulos(2); tulokset.lisaa(pitsi23); 
    Tulos pitsi51 = new Tulos(5); tulokset.lisaa(pitsi51); 
    List<Tulos> loytyneet; 
    loytyneet = tulokset.annaTulokset(3); 
    assertEquals("From: Tulokset line: 119", 0, loytyneet.size()); 
    loytyneet = tulokset.annaTulokset(1); 
    assertEquals("From: Tulokset line: 121", 2, loytyneet.size()); 
    assertEquals("From: Tulokset line: 122", true, loytyneet.get(0) == pitsi11); 
    assertEquals("From: Tulokset line: 123", true, loytyneet.get(1) == pitsi12); 
    loytyneet = tulokset.annaTulokset(5); 
    assertEquals("From: Tulokset line: 125", 1, loytyneet.size()); 
    assertEquals("From: Tulokset line: 126", true, loytyneet.get(0) == pitsi51); 
  } // Generated by ComTest END
}