package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.14 14:20:37 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TulosTest {


  // Generated by ComTest BEGIN
  /** testRekisteroi102 */
  @Test
  public void testRekisteroi102() {    // Tulos: 102
    Tulos tulos1 = new Tulos(); 
    assertEquals("From: Tulos line: 104", 0, tulos1.getTunnusNro()); 
    tulos1.rekisteroi(); 
    Tulos tulos2 = new Tulos(); 
    tulos2.rekisteroi(); 
    int n1 = tulos1.getTunnusNro(); 
    int n2 = tulos2.getTunnusNro(); 
    assertEquals("From: Tulos line: 110", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse249 */
  @Test
  public void testParse249() {    // Tulos: 249
    Tulos tulos = new Tulos(); 
    tulos.parse("   2   |  10  |   Kalastus  | 1949 | 22 t "); 
    assertEquals("From: Tulos line: 252", 10, tulos.getPaivaNro()); 
    assertEquals("From: Tulos line: 253", "2|10|Kalastus|1949|22", tulos.toString()); 
    tulos.rekisteroi(); 
    int n = tulos.getTunnusNro(); 
    tulos.parse(""+(n+20)); 
    tulos.rekisteroi(); 
    assertEquals("From: Tulos line: 259", n+20+1, tulos.getTunnusNro()); 
    assertEquals("From: Tulos line: 260", "" + (n+20+1) + "|10|Kalastus|1949|22", tulos.toString()); 
  } // Generated by ComTest END
}