package treenipaivakirja.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treenipaivakirja.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.04.12 22:36:52 // Generated by ComTest
 *
 */
@SuppressWarnings("all")
public class TulosTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi102 */
  @Test
  public void testRekisteroi102() {    // Tulos: 102
    Tulos tulos1 = new Tulos(); 
    assertEquals("From: Tulos line: 104", 0, tulos1.getTunnusNro()); 
    tulos1.rekisteroi(); 
    Tulos tulos2 = new Tulos(); 
    tulos2.rekisteroi(); 
    int n1 = tulos1.getTunnusNro(); 
    int n2 = tulos2.getTunnusNro(); 
    assertEquals("From: Tulos line: 110", n2-1, n1); 
  } // Generated by ComTest END
}